package liber.enumeration;

public enum ErrorCode {
	ERROR_READING_STREAM,
	REQUEST_ERROR_NO_REQUEST,
	REQUEST_ERROR_NAME,
	REQUEST_ERROR_RECIPIENT,
	REQUEST_ERROR_SENDER,
	REQUEST_ERROR_NAME_MISSING,
	REQUEST_ERROR_SENDER_MISSING,
	REQUEST_ERROR_RECIPIENT_MISSING,
	REQUEST_ERROR_SECRET_MISSING,
	REQUEST_ERROR_FIELD_MISSING,
	RESPONSE_ERROR_GOOD_FIELD_MISSING,
	RESPONSE_ERROR_BAD_FIELD_MISSING,
	RESPONSE_ERROR_MISSING_STATUS,
	REQUEST_ERROR_UNKNOWN_REQUEST,
	ERROR_OUTLINK_UNKNOWN,
	ERROR_INLINK,
	ERROR_USER_ADDRESS,
	ERROR_CONTACT,
	ERROR_MICROTIME_FORMAT,
	ERROR_NO_MESSAGE,
	ERROR_HASH,
	REQUEST_ERROR_SENDER_IS_RECIPIENT,
	ERROR_SECRET
}
