package liber.request;

public enum RequestName {
	captchaForCreation,
	captchaForDeletion,
	checkPostedMessage,
	contactDataDeleted,
	contactDataUpdated,
	createAccount,
	deleteAccount,
	getCaptchaImageForCreation,
	getCaptchaImageForDeletion,
	getNextPostedMessage,
	getNextPosted,
	getServerPlace,
	linkAccepted,
	linkCancelled,
	linkDeleted,
	linkOffer,
	linkRefused,
	login,
	logout,
	messageAcknowledgment,
	message,
	nextPostedMessageReceived,
	nextPostedReceived,
	nowOffline,
	nowOnlineAcknowledgment,
	nowOnline,
	postLater,
	postMessage
}
